repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

  - repo: https://github.com/ikamensh/flynt/
    rev: '1.0.6'
    hooks:
      - id: flynt

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        exclude: (.*)/migrations

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: '7.0.0'
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        additional_dependencies: [ '.[toml]' ]

  - repo: https://github.com/PyCQA/pylint
    # Configuration help can be found here:
    # https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
    rev: v4.0.0
    hooks:
      - id: pylint
        alias: pylint-with-spelling
        stages: [ manual ]
        language: system
        types: [ python ]
        require_serial: true
        exclude:
          (?x)^(
          docs/.*|
          test/.*
          )$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean

  - repo: https://github.com/pycqa/doc8
    rev: v2.0.0
    hooks:
      - id: doc8
